### ISSUE TITLE
Cache/Photo Storage Bug

### ISSUE THREAD

**Issue by theinfinityproject** [microlinkhq/splashy#8]
OS: Win 10 1803

C:\Users\$USER\AppData\Roaming\Splashy\Photos should only keep the last 100 pictures otherwise it fills the hdd indefinitly. I run out of space this morning and when i checked i had 180GB photos stored in \AppData\Roaming\Splashy\Photos.

**Comment by Kikobeats** [comment]
The temporal file at url mode is removed using fs binding
https://github.com/microlinkhq/splashy/blob/master/index.js#L46

**Comment by Kikobeats** [comment]
I updated how we handle temporal on the new `v3.0.0`, please consider upgrade 🙂
